name: List all repositories in an Organization


on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List Org Repos
      id: list-all-repos
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        PAGE=1
        REPO_NAMES=()
        while :; do
          URL="https://api.github.com/orgs/stemdo-labs/repos?page=$PAGE&per_page=100"
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$URL")
          REPOS=$(echo "$RESPONSE" | jq -r '.[].name')

          if [ -z "$REPOS" ]; then
            break
          fi

          for NAME in $REPOS; do
            REPO_NAMES+=("$NAME")
          done

          PAGE=$((PAGE + 1))
        done

        echo "${REPO_NAMES[@]}" | jq -R . | jq -s . > repos.json
        cat repos.json
    
    - name: Commit and Push JSON File
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add repos.json
        git commit -m 'Add repos.json with list of all repositories'
        git push origin HEAD:main
