name: List all repositories in an Organization


on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate GithubApp token
      id: repos-token
      uses: getsentry/action-github-app-token@v3
      with:
        app_id: ${{ secrets.DELETEMEPLEASESTEMDO_APP_ID }}
        private_key: ${{ secrets.DELETEMEPLEASESTEMDO_PRIVATE_KEY }}

    - name: List Org Repos
      id: list-all-repos
      env:
        TOKEN: ${{ steps.repos-token.outputs.token }}
      run: |
        PAGE=1
        ALL_REPOS=()
        while :; do
          URL="https://api.github.com/orgs/stemdo-labs/repos?page=$PAGE&per_page=100"
          if [ -n "$TOKEN" ]; then
            RESPONSE=$(curl -s -H "Authorization: token $TOKEN" "$URL")
          else
            RESPONSE=$(curl -s "$URL")
          fi

          REPOS=$(echo "$RESPONSE" | jq -r '.[].name')

          if [ -z "$REPOS" ]; then
              break
          fi

          for REPO in $REPOS; do
            ALL_REPOS+=("\"$REPO\"")
          done
          
          PAGE=$((PAGE + 1))
        done
        echo "$ALL_REPOS"
        echo "[${ALL_REPOS[*]}]" | sed 's/" "/","/g' > repos.json
        echo "-------------------------"
        cat repos.json
    
    - name: Commit and Push JSON File
      env:
        GITHUB_TOKEN: ${{ steps.repos-token.outputs.token }}
        GH_USER: ${{ secrets.GH_USER }}
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
      run: |
        git config --global user.name $GH_USER
        git config --global user.email $GH_EMAIL
        git add repos.json
        git commit -m 'Add repos.json with list of all repositories'
        git push origin private-repos

    # - name: GitHub Commit & Push
    #   uses: actions-js/push@v1.5
    #   with:
    #     github_token: ${{ steps.repos-token.outputs.token }}
    #     message: 'Add repos.json with list of all repositories'
    #     branch: 'private-repos'
            
