name: Convert Repositories to Private

on:
  workflow_dispatch:

jobs:
  read-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read repository names from JSON
      id: read_repos
      run: |
        echo "Reading repository names from repos.json"
        REPO_NAMES=$(jq -c '.' repos.json)
        echo "REPO_NAMES=$REPO_NAMES" >> $GITHUB_ENV

    - name: Print env
      run: |
        echo "${{ github.env.REPO_NAMES }}"

  # convert_to_private:
  #   needs: read-repos
  #   runs-on: ubuntu-latest
  #   # strategy:
  #   #   matrix:
  #   #     repo: ${{ fromJson(github.env.REPO_NAMES) }}

  #   steps:
  #   - name: Convert repository to private
  #   #   env:
  #   #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #   #     REPO_NAME: ${{ matrix.repo }}
  #   #     OWNER: ${{ github.repository_owner }}
  #     run: |
  #       echo "${{ env.REPO_NAMES }}"
