name: Convert Repositories to Private

on:
  workflow_dispatch:

jobs:
  read-repos:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.read-repos.outputs.REPO_NAMES }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Read repository names from JSON
      id: read-repos
      run: |
        echo "Reading repository names from repos.json"
        REPO_NAMES=$(jq -c '.' repos.json)
        echo "REPO_NAMES=$REPO_NAMES" >> $GITHUB_OUTPUT

  convert_to_private:
    needs: [read-repos]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.read-repos.outputs.repos) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install axios

    - name: Generate GithubApp token
      id: repos-token
      uses: getsentry/action-github-app-token@v3
      with:
        app_id: ${{ secrets.DELETEMEPLEASESTEMDO_APP_ID }}
        private_key: ${{ secrets.DELETEMEPLEASESTEMDO_PRIVATE_KEY }}
        
    - name: Convert repository to private
      env:
        REPO_NAME: ${{ matrix.repo }}
        OWNER: ${{ github.repository_owner }}
        TOKEN: ${{ steps.repos-token.outputs.token  }}
      run: |
        node set-private-repo.js \
          ${{ matrix.repo }} \
          ${{ github.repository_owner }} \