name: Convert Repositories to Private

on:
  workflow_dispatch:

jobs:
  read-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read repository names from JSON
      id: read_repos
      run: |
        echo "Reading repository names from repos.json"
        REPO_NAMES=$(jq -c '.' repos.json)
        echo "$REPO_NAMES"
        echo "repos=$REPO_NAMES" >> $GITHUB_OUTPUT

  convert_to_private:
    needs: read-repos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.read-repos.outputs.repos) }}

    steps:
    - name: Convert repository to private
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: ${{ matrix.repo }}
        OWNER: ${{ github.repository_owner }}
      run: |
        echo "Converting $REPO_NAME to private"
        curl -X PATCH \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$OWNER/$REPO_NAME \
          -d '{"private": true}'
