name: Convert Repositories to Private

on:
  workflow_dispatch:

jobs:
  read-repos:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.read-repos.outputs.REPO_NAMES }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Read repository names from JSON
      id: read-repos
      run: |
        echo "Reading repository names from repos.json"
        REPO_NAMES=$(jq -c '.' repos.json)
        echo "REPO_NAMES=$REPO_NAMES" >> $GITHUB_OUTPUT

  convert_to_private:
    needs: [read-repos]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.read-repos.outputs.repos) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate GithubApp token
      id: repos-token
      uses: getsentry/action-github-app-token@v3
      with:
        app_id: ${{ secrets.DELETEMEPLEASESTEMDO_APP_ID }}
        private_key: ${{ secrets.DELETEMEPLEASESTEMDO_PRIVATE_KEY }}
        
    - name: Convert repository to private
      env:
        REPO_NAME: ${{ matrix.repo }}
        OWNER: ${{ github.repository_owner }}
        TOKEN: ${{ steps.repos-token.outputs.token  }}
      run: |
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$OWNER/$REPO_NAME \
          -d '{"private": true}')

        echo "Response code: $RESPONSE"
        if [ "$RESPONSE" -ne 200 ]; then
          echo "Failed to convert $REPO_NAME to private. HTTP status code: $RESPONSE"
          cat response.json
          exit 1
        fi