name: Convert Repositories to Private

on:
  workflow_dispatch:
    inputs:
      repo_names:
        description: 'Comma-separated list of repository names to convert'
        required: true

jobs:
  convert_to_private:
    runs-on: ubuntu-latest

    steps:
    - name: Convert repositories to private
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        REPO_NAMES: ${{ github.event.inputs.repo_names }}
        OWNER: ${{ github.repository_owner }}
      run: |
        IFS=',' read -r -a REPO_ARRAY <<< "$REPO_NAMES"
        for REPO_NAME in "${REPO_ARRAY[@]}"; do
          echo "Converting $REPO_NAME to private"
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO_NAME \
            -d '{"private": true}'
        done
